set search_path to fmk;
drop table if exists semaphores_f18_rules;
drop table if exists semaphores_rj;
drop table if exists semaphores_lokal;
drop table if exists semaphores_ops;
drop table if exists semaphores_banke;
drop table if exists semaphores_refer;
drop table if exists semaphores_tnal;
drop table if exists semaphores_tdok;
drop table if exists semaphores_tarifa;
drop table if exists semaphores_koncij;
drop table if exists semaphores_vrstep;
drop table if exists semaphores_pkonto;
drop table if exists semaphores_fakt_objekti;
drop table if exists semaphores_ks;
set search_path to public;
